version: '3'
services:
  php-fpm:
    image: php:7.2-fpm-alpine
    container_name: php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 8888:8888
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  
  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'craftbeers'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
    expose:
      - '3306'